version: '3'

services:
  fastapi:
    build: fastapi/
    ports: 
      - 8001:8001
    networks:
      - deploy_network
    container_name: fastapi
    volumes:
      - ./fastapi:/fastapi  # 将 fastapi 的目录映射到 本地 

  streamlit:
    build: streamlit/
    depends_on:
      - fastapi
    ports: 
      - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit
    volumes:
      - ./streamlit:/streamlit  # 将 streamlit 的目录映射到 本地
      - ./fastapi:/fastapi  # 将 fastapi 的目录映射到 streamlit 中

networks:
  deploy_network:
    driver: bridge
